# Try to recall all values that count as falsy in Python.
print(0)
print(None)
print(0.0)
print(False)
print('empty sequences')
print('empty objects')
print('empty collections')
print(repr(''))
print(repr(()))
print(repr([]))
print(repr({}))
print(set())
print('range()')